export const CATEGORIES = [
  "Bicicletas",
  "Vehículos y motor",
  "Informática",
  "Telefonía",
  "Consolas y videojuegos",
  "Imagen y sonido",
  "Moda y complementos",
  "Música",
  "Casa y jardín",
  "Libros",
  "Deportes",
  "Juegos y juguetes",
  "Coleccionismo",
  "Arte y antigüedades",
  "Ocio y cultura",
] as const;

export const CATEGORY_EMOJI: Record<string, string> = {
  Bicicletas: "🚲",
  "Vehículos y motor": "🚗",
  Informática: "💻",
  Telefonía: "📱",
  "Consolas y videojuegos": "🎮",
  "Imagen y sonido": "🎧",
  "Moda y complementos": "🧥",
  Música: "🎸",
  "Casa y jardín": "🍳",
  Libros: "📚",
  Deportes: "🏋️",
  "Juegos y juguetes": "🧸",
  Coleccionismo: "🗃️",
  "Arte y antigüedades": "🖼️",
  "Ocio y cultura": "🎟️",
};
