import type { Item } from "./types";

function unsplash(photoId: string) {
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=800&q=75`;
}

export const MOCK_ITEMS: Item[] = [
  {
    id: "1",
    title: "Bicicleta rodado 26, poco uso",
    category: "Bicicletas",
    emoji: "🚲",
    imageUrl: unsplash("photo-1485965120184-e220f721d03e"),
    condition: "usado",
    lookingFor: ["Tecnología", "Deportes"],
    ownerName: "Marina",
    ownerLocation: "Palermo, CABA",
    ownerRating: 4.8,
  },
  {
    id: "2",
    title: "Consola PS5 + 2 controles",
    category: "Tecnología",
    emoji: "🎮",
    imageUrl: unsplash("photo-1607853202273-797f1c22a38e"),
    condition: "como_nuevo",
    lookingFor: ["Bicicletas", "Música"],
    ownerName: "Julián",
    ownerLocation: "Belgrano, CABA",
    ownerRating: 4.6,
  },
  {
    id: "3",
    title: "Campera de cuero talle M",
    category: "Ropa",
    emoji: "🧥",
    imageUrl: unsplash("photo-1623854156816-4c4fc355ffc7"),
    condition: "usado",
    lookingFor: ["Libros", "Música"],
    ownerName: "Sofía",
    ownerLocation: "La Plata",
    ownerRating: 5,
  },
  {
    id: "4",
    title: "Guitarra criolla + funda",
    category: "Música",
    emoji: "🎸",
    imageUrl: unsplash("photo-1588690224648-20426ab6274a"),
    condition: "usado",
    lookingFor: ["Ropa", "Hogar"],
    ownerName: "Tomás",
    ownerLocation: "Rosario",
    ownerRating: 4.9,
  },
  {
    id: "5",
    title: "Set de ollas antiadherentes",
    category: "Hogar",
    emoji: "🍳",
    imageUrl: unsplash("photo-1584990347193-6bebebfeaeee"),
    condition: "nuevo",
    lookingFor: ["Libros", "Ropa"],
    ownerName: "Carla",
    ownerLocation: "Córdoba",
    ownerRating: 4.7,
  },
  {
    id: "6",
    title: "Colección 20 libros de fantasía",
    category: "Libros",
    emoji: "📚",
    imageUrl: unsplash("photo-1595123550384-b81222e23cf9"),
    condition: "usado",
    lookingFor: ["Tecnología", "Hogar"],
    ownerName: "Nico",
    ownerLocation: "Mendoza",
    ownerRating: 4.5,
  },
  {
    id: "7",
    title: "Pesas ajustables 20kg",
    category: "Deportes",
    emoji: "🏋️",
    imageUrl: unsplash("photo-1638536532686-d610adfc8e5c"),
    condition: "como_nuevo",
    lookingFor: ["Bicicletas", "Tecnología"],
    ownerName: "Ailén",
    ownerLocation: "Palermo, CABA",
    ownerRating: 4.9,
  },
  {
    id: "8",
    title: "Notebook i5 8GB RAM",
    category: "Tecnología",
    emoji: "💻",
    imageUrl: unsplash("photo-1541807084-5c52b6b3adef"),
    condition: "usado",
    lookingFor: ["Música", "Deportes"],
    ownerName: "Facundo",
    ownerLocation: "San Isidro, BA",
    ownerRating: 4.4,
  },
];
